apiVersion: v2
name: oceanbase-cluster
description: A Helm chart for Kubernetes to deploy OceanBase cluster

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
<<<<<<< HEAD
version: 4.3.1-sp.0-100000032024051615
=======
version: 4.3.1-sp.0-100000032024051615
>>>>>>> 87bb04ab2155b979538c6f6462933f0f86c59cfe

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
<<<<<<< HEAD
appVersion: 4.3.1.0-100000032024051615
=======
appVersion: 4.3.1.0-100000032024051615
>>>>>>> 87bb04ab2155b979538c6f6462933f0f86c59cfe
