apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBTenantBackupPolicy
metadata:
  labels:
    ref-obcluster: test
    app.kubernetes.io/name: obtenantbackuppolicy
    app.kubernetes.io/instance: obtenantbackuppolicy-sample
    app.kubernetes.io/part-of: ob-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ob-operator
  name: obtenantbackuppolicy-sample
  namespace: oceanbase
spec:
  obClusterName: "test"
  tenantName: "t1"
  tenantSecret: "t1-credential"
  jobKeepWindow: "1d"
  dataClean:
    recoveryWindow: "8d"
  logArchive:
    destination:
      type: "NFS"
      path: "log_archive_custom"
    switchPieceInterval: "1d"
  dataBackup:
    destination:
      type: "NFS"
      path: "data_backup_custom"
    fullCrontab: "30 0 * * 6"
    incrementalCrontab: "30 1 * * *"