apiVersion: oceanbase.oceanbase.com/v1alpha1		
kind: OBTenant		
metadata:		
  name: t1s
  namespace: oceanbase
spec:	
  obcluster: test
  tenantName: t1s
  unitNum: 1 
  charset: utf8mb4  
  connectWhiteList: '%'
  forceDelete: true
  tenantRole: STANDBY
  credentials:
    root: t1s-root
    standbyRo: t1s-ro
  source:
    restore:
      sourceUri: "file:///ob-backup/t1/data_backup_custom1,file:///ob-backup/t1/log_archive_custom1"
      until: 
        unlimited: true
      replayLogUntil:
        unlimited: true
    tenant: t1
  pools:
    - zone: zone1
      type: 
        name: Full 
        replica: 1
        isActive: true
      resource:
        maxCPU: 1000m 
        memorySize: 2Gi 
        minCPU: 1 
        maxIops: 1024 
        minIops: 1024
        logDiskSize: 
    - zone: zone2
      type: 
        name: Full
        replica: 1
        isActive: true
      resource:
        maxCPU: 1000m 
        memorySize: 2Gi
        minCPU: 1 
        maxIops: 1024
        minIops: 1024
        iopsWeight: 2
        logDiskSize: 4Gi 
    - zone: zone3
      type: 
        name: Full
        replica: 1
        isActive: true
      priority: 3
      resource:
        maxCPU: 1000m 
        memorySize: 2Gi
        minCPU: 1
        maxIops: 1024
        minIops: 1024
        iopsWeight: 2
        logDiskSize: 4Gi 
