apiVersion: oceanbase.oceanbase.com/v1alpha1		
kind: OBTenant		
metadata:		
  name: t1ss
  namespace: oceanbase
spec:	
  obcluster: test
  tenantName: t1ss
  unitNum: 1 
  charset: utf8mb4  
  connectWhiteList: '%'
  forceDelete: true
  credentials:
    root: t1s-root
    standbyRo: t1s-ro
  source:
    tenant: t1
  tenantRole: STANDBY
  pools:
    - zone: zone1
      type: 
        name: FUll 
        replica: 1
        isActive: true
      resource:
        maxCPU: 1000m 
        memorySize: 2Gi 
        minCPU: 1 
        maxIops: 1024 
        minIops: 1024
        iopsWeight:
        logDiskSize: 
    - zone: zone2
      type: 
        name: Full
        replica: 1
        isActive: true
      resource:
        maxCPU: 1000m 
        memorySize: 2Gi
        minCPU: 1 
        maxIops: 1024
        minIops: 1024
        iopsWeight: 2
        logDiskSize: 4Gi 
    - zone: zone3
      type: 
        name: Full
        replica: 1
        isActive: true
      priority: 3
      resource:
        maxCPU: 1000m 
        memorySize: 2Gi
        minCPU: 1
        maxIops: 1024
        minIops: 1024
        iopsWeight: 2
        logDiskSize: 4Gi 
