apiVersion: cloud.oceanbase.com/v1		
kind: Tenant		
metadata:		
  name: tenant1		
  namespace: obcluster		
spec:	
  # 必填
  clusterName: ob-test		
  clusterID: 1
  # 非必填
  charset:  # 租户的字符集
  collate:  # 租户校对规则

  variables: 
    - name: ob_tcp_invited_nodes
      value: '%'

  topology:
    - zone: zone1
      unitNum: 1 # 指定要创建的单个 ZONE 下的单元个数，取值要小于单个 ZONE 中的 OBServer 个数。
      type: 
        name: FUll # FULL READONLY LOGONLY , 需要写出完整类型, 大小写不敏感
        replica: 1 # FULL 和 LOGONLY 类型只能设置1
      priority: 3 # 可选，表示当前zone的优先级，数字越大优先级越高，没有填写的放在最后面
      resource:
        maxCPU: 2500m # 租户可用最大 CPU 数。
        memorySize: 1Gi # 租户可用内存。
        # 非必填
        minCPU: 2 # 租户可用最小 CPU 数。
        maxIops: 1024 # 租户 IOPS 最多数量。
        minIops: 1024 # 租户 IOPS 最少数量。
         # v3
        maxDiskSize:  # 租户可用最大磁盘空间。
        maxSessionNum:  # 租户最大 SESSION 数。
         # v4
        iopsWeight: 
        logDiskSize: 
    - zone: zone2
      unitNum: 1
      type: 
        name: Full
        replica: 1
      priority: 3
      resource:
        maxCPU: 2500m 
        memorySize: 1Gi
        # 非必填
        minCPU: 2 
        maxIops: 256
        minIops: 256
         # v3
        maxDiskSize: 1Gi
        maxSessionNum: 64 
         # v4
        iopsWeight: 2
        logDiskSize: 4Gi 
    - zone: zone3
      unitNum: 1
      type: 
        name: Full
        replica: 1
      priority: 3
      resource:
        maxCPU: 2500m 
        memorySize: 1Gi
        # 非必填
        minCPU: 2 
        maxIops: 256
        minIops: 256
         # v3
        maxDiskSize: 1Gi
        maxSessionNum: 64 
         # v4
        iopsWeight: 2
        logDiskSize: 4Gi 

