apiVersion: v1
kind: Service
metadata:
  name: svc-ob-configserver
  # namespace: oceanbase
spec:
  type: NodePort
  selector:
    app: ob-configserver
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ob-configserver
  # namespace: oceanbase
spec:
  selector:
    matchLabels:
      app: ob-configserver
  replicas: 1
  template:
    metadata:
      labels:
        app: ob-configserver
    spec:
      containers:
        - name: ob-configserver
          image: oceanbase/ob-configserver:1.0.0-2
          ports:
            - containerPort: 8080
              name: "http"
          env:
            - name: DATABASE_TYPE
              value: sqlite3
            - name: SVC_ADDRESS
              value: $(SVC_OB_CONFIGSERVER_SERVICE_HOST)
            - name: SVC_PORT
              value: $(SVC_OB_CONFIGSERVER_SERVICE_PORT)
          resources:
            limits:
              memory: 2Gi


