
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: tenants.cloud.oceanbase.com
spec:
  group: cloud.oceanbase.com
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Tenant is the Schema for the tenants API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TenantSpec defines the desired state of Tenant
            properties:
              charset:
                type: string
              clusterID:
                type: integer
              clusterName:
                type: string
              collate:
                type: string
              mode:
                type: string
              topology:
                items:
                  properties:
                    priority:
                      type: integer
                    resource:
                      properties:
                        iopsWeight:
                          description: V4
                          type: integer
                        logDiskSize:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        maxCPU:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        maxDiskSize:
                          anyOf:
                          - type: integer
                          - type: string
                          description: V3
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        maxIops:
                          type: integer
                        maxSessionNum:
                          type: integer
                        memorySize:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        minCPU:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        minIops:
                          type: integer
                      required:
                      - maxCPU
                      - memorySize
                      type: object
                    type:
                      properties:
                        name:
                          type: string
                        replica:
                          type: integer
                      required:
                      - name
                      type: object
                    unitNum:
                      type: integer
                    zone:
                      type: string
                  required:
                  - resource
                  - type
                  - unitNum
                  - zone
                  type: object
                type: array
              variables:
                items:
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                  required:
                  - name
                  - value
                  type: object
                type: array
            required:
            - clusterID
            - clusterName
            - topology
            type: object
          status:
            description: TenantStatus defines the observed state of Tenant
            properties:
              charset:
                type: string
              status:
                type: string
              topology:
                items:
                  properties:
                    priority:
                      type: integer
                    resource:
                      properties:
                        iopsWeight:
                          description: V4
                          type: integer
                        logDiskSize:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        maxCPU:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        maxDiskSize:
                          anyOf:
                          - type: integer
                          - type: string
                          description: V3
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        maxIops:
                          type: integer
                        maxSessionNum:
                          type: integer
                        memorySize:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        minCPU:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        minIops:
                          type: integer
                      required:
                      - maxCPU
                      - memorySize
                      type: object
                    type:
                      properties:
                        name:
                          type: string
                        replica:
                          type: integer
                      required:
                      - name
                      type: object
                    unitNum:
                      type: integer
                    units:
                      items:
                        properties:
                          migrate:
                            properties:
                              serverIP:
                                type: string
                              serverPort:
                                type: integer
                            required:
                            - serverIP
                            - serverPort
                            type: object
                          serverIP:
                            type: string
                          serverPort:
                            type: integer
                          status:
                            type: string
                          unitId:
                            type: integer
                        required:
                        - migrate
                        - serverIP
                        - serverPort
                        - status
                        - unitId
                        type: object
                      type: array
                    zone:
                      type: string
                  required:
                  - resource
                  - type
                  - unitNum
                  - units
                  - zone
                  type: object
                type: array
            required:
            - status
            - topology
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
