
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: restores.cloud.oceanbase.com
spec:
  group: cloud.oceanbase.com
  names:
    kind: Restore
    listKind: RestoreList
    plural: restores
    singular: restore
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Restore is the Schema for the restores API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RestoreSpec defines the desired state of Restore
            properties:
              dest:
                description: DestSpec defines the dest of restore
                properties:
                  clusterID:
                    format: int64
                    type: integer
                  clusterName:
                    type: string
                  kmsEncryptInfo:
                    type: string
                  tenant:
                    type: string
                  topology:
                    items:
                      properties:
                        priority:
                          type: integer
                        resource:
                          properties:
                            maxCPU:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            maxDiskSize:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            maxIops:
                              type: integer
                            maxMemory:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            maxSessionNum:
                              type: integer
                            minCPU:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            minIops:
                              type: integer
                            minMemory:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                          required:
                          - maxCPU
                          - maxMemory
                          - minCPU
                          - minMemory
                          type: object
                        type:
                          properties:
                            name:
                              type: string
                            replica:
                              type: integer
                          required:
                          - name
                          type: object
                        unitNum:
                          type: integer
                        zone:
                          type: string
                      required:
                      - resource
                      - type
                      - unitNum
                      - zone
                      type: object
                    type: array
                required:
                - clusterID
                - clusterName
                - kmsEncryptInfo
                - tenant
                - topology
                type: object
              parameters:
                items:
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                  required:
                  - name
                  - value
                  type: object
                type: array
              savePoint:
                description: SavePointSpec defines the savepoint to restore to
                properties:
                  type:
                    type: string
                  value:
                    type: string
                required:
                - type
                - value
                type: object
              secret:
                type: string
              source:
                description: SourceSpec defines the source of restore
                properties:
                  clusterID:
                    format: int64
                    type: integer
                  clusterName:
                    type: string
                  path:
                    description: PathSpec defines the data path, for oceanbase 3.x,
                      use root, for oceanbase 4.x, use data and log
                    properties:
                      data:
                        type: string
                      log:
                        type: string
                      root:
                        type: string
                    required:
                    - data
                    - log
                    - root
                    type: object
                  tenant:
                    type: string
                required:
                - clusterID
                - clusterName
                - path
                - tenant
                type: object
            required:
            - dest
            - savePoint
            - source
            type: object
          status:
            description: RestoreStatus defines the observed state of Restore
            properties:
              finishTimestamp:
                type: string
              jobID:
                format: int64
                type: integer
              status:
                type: string
            required:
            - finishTimestamp
            - jobID
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
