---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.0
  name: obtenantbackups.oceanbase.oceanbase.com
spec:
  group: oceanbase.oceanbase.com
  names:
    kind: OBTenantBackup
    listKind: OBTenantBackupList
    plural: obtenantbackups
    singular: obtenantbackup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.type
      name: Type
      type: string
    - jsonPath: .status.status
      name: Status
      type: string
    - jsonPath: .spec.tenantName
      name: TenantName
      type: string
    - jsonPath: .spec.path
      name: Path
      priority: 100
      type: string
    - jsonPath: .status.startedAt
      name: StartedAt
      type: string
    - description: In ArchiveLogJob, EndedAt is CheckpointScnDisplay field, in other
        jobs, EndedAt is EndTimestamp field
      jsonPath: .status.endedAt
      name: EndedAt
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: |-
          OBTenantBackup is the Schema for the obtenantbackups API.
          An instance of OBTenantBackup stands for a tenant backup job
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: OBTenantBackupSpec defines the desired state of OBTenantBackup
            properties:
              encryptionSecret:
                type: string
              obClusterName:
                type: string
              path:
                type: string
              tenantName:
                type: string
              tenantSecret:
                type: string
              type:
                type: string
            required:
            - obClusterName
            - tenantName
            - tenantSecret
            - type
            type: object
          status:
            description: OBTenantBackupStatus defines the observed state of OBTenantBackup
            properties:
              archiveLogJob:
                description: OBArchiveLogJob is equal to OBArchiveLogSummary, but
                  match view DBA_OB_ARCHIVELOG_JOBS
                properties:
                  base_piece_id:
                    format: int64
                    type: integer
                  checkpoint_scn:
                    format: int64
                    type: integer
                  checkpoint_scn_display:
                    type: string
                  comment:
                    type: string
                  compatible:
                    type: string
                  compression_ratio:
                    type: string
                  deleted_input_bytes:
                    format: int64
                    type: integer
                  deleted_input_bytes_display:
                    type: string
                  deleted_output_bytes:
                    format: int64
                    type: integer
                  deleted_output_bytes_display:
                    type: string
                  dest_id:
                    format: int64
                    type: integer
                  dest_no:
                    format: int64
                    type: integer
                  input_bytes:
                    format: int64
                    type: integer
                  input_bytes_display:
                    type: string
                  output_bytes:
                    format: int64
                    type: integer
                  output_bytes_display:
                    type: string
                  path:
                    type: string
                  piece_switch_interval:
                    type: string
                  round_id:
                    format: int64
                    type: integer
                  start_scn:
                    format: int64
                    type: integer
                  start_scn_display:
                    type: string
                  status:
                    type: string
                  tenant_id:
                    format: int64
                    type: integer
                  used_piece_id:
                    format: int64
                    type: integer
                required:
                - base_piece_id
                - checkpoint_scn
                - checkpoint_scn_display
                - comment
                - compatible
                - compression_ratio
                - deleted_input_bytes
                - deleted_input_bytes_display
                - deleted_output_bytes
                - deleted_output_bytes_display
                - dest_id
                - dest_no
                - input_bytes
                - input_bytes_display
                - output_bytes
                - output_bytes_display
                - path
                - piece_switch_interval
                - round_id
                - start_scn
                - status
                - tenant_id
                - used_piece_id
                type: object
              backupJob:
                description: OBBackupJob matches view DBA_OB_BACKUP_JOBS & DBA_OB_BACKUP_JOB_HISTORY
                properties:
                  backup_set_id:
                    format: int64
                    type: integer
                  backup_type:
                    type: string
                  comment:
                    type: string
                  encryption_mode:
                    type: string
                  end_timestamp:
                    type: string
                  executor_tenant_id:
                    format: int64
                    type: integer
                  job_id:
                    format: int64
                    type: integer
                  job_level:
                    type: string
                  passwd:
                    type: string
                  plus_archivelog:
                    type: string
                  result:
                    type: string
                  start_timestamp:
                    type: string
                  status:
                    type: string
                  tenant_id:
                    format: int64
                    type: integer
                required:
                - backup_set_id
                - backup_type
                - comment
                - encryption_mode
                - executor_tenant_id
                - job_id
                - job_level
                - passwd
                - plus_archivelog
                - result
                - start_timestamp
                - status
                - tenant_id
                type: object
              dataCleanJob:
                description: OBBackupCleanJob matches view DBA_OB_BACKUP_DELETE_JOBS
                  & DBA_OB_BACKUP_DELETE_JOB_HISTORY
                properties:
                  comment:
                    type: string
                  end_timestamp:
                    type: string
                  executor_tenant_id:
                    format: int64
                    type: integer
                  job_id:
                    format: int64
                    type: integer
                  job_level:
                    type: string
                  parameter:
                    type: string
                  result:
                    type: string
                  start_timestamp:
                    type: string
                  status:
                    type: string
                  success_task_count:
                    format: int64
                    type: integer
                  task_count:
                    format: int64
                    type: integer
                  tenant_id:
                    format: int64
                    type: integer
                  type:
                    type: string
                required:
                - comment
                - executor_tenant_id
                - job_id
                - job_level
                - parameter
                - result
                - start_timestamp
                - status
                - success_task_count
                - task_count
                - tenant_id
                - type
                type: object
              endedAt:
                type: string
              operationContext:
                properties:
                  failureRule:
                    properties:
                      failureStatus:
                        type: string
                      failureStrategy:
                        type: string
                      maxRetry:
                        type: integer
                      retryCount:
                        type: integer
                    required:
                    - failureStatus
                    - failureStrategy
                    type: object
                  idx:
                    type: integer
                  name:
                    type: string
                  targetStatus:
                    type: string
                  task:
                    type: string
                  taskId:
                    type: string
                  taskStatus:
                    type: string
                  tasks:
                    items:
                      type: string
                    type: array
                required:
                - idx
                - name
                - targetStatus
                - task
                - taskId
                - taskStatus
                - tasks
                type: object
              progress:
                type: string
              startedAt:
                type: string
              status:
                description: |-
                  INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
                  Important: Run "make" to regenerate code after modifying this file
                type: string
            required:
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
