---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: obtenantrestores.oceanbase.oceanbase.com
spec:
  group: oceanbase.oceanbase.com
  names:
    kind: OBTenantRestore
    listKind: OBTenantRestoreList
    plural: obtenantrestores
    singular: obtenantrestore
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .spec.targetTenant
      name: TargetTenant
      type: string
    - jsonPath: .spec.targetCluster
      name: TargetCluster
      type: string
    - jsonPath: .spec.restoreRole
      name: RestoreRole
      type: string
    - jsonPath: .status.restoreProgress.status
      name: StatusInDB
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: OBTenantRestore is the Schema for the obtenantrestores API An
          instance of OBTenantRestore stands for a tenant restore job
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OBTenantRestoreSpec defines the desired state of OBTenantRestore
            properties:
              primaryTenant:
                type: string
              restoreOption:
                type: string
              restoreRole:
                type: string
              source:
                properties:
                  archiveSource:
                    properties:
                      ossAccessSecret:
                        type: string
                      path:
                        type: string
                      type:
                        type: string
                    required:
                    - path
                    type: object
                  bakDataSource:
                    properties:
                      ossAccessSecret:
                        type: string
                      path:
                        type: string
                      type:
                        type: string
                    required:
                    - path
                    type: object
                  bakEncryptionSecret:
                    type: string
                  cancel:
                    type: boolean
                  description:
                    type: string
                  replayLogUntil:
                    properties:
                      scn:
                        type: string
                      timestamp:
                        type: string
                      unlimited:
                        type: boolean
                    type: object
                  sourceUri:
                    type: string
                  until:
                    properties:
                      scn:
                        type: string
                      timestamp:
                        type: string
                      unlimited:
                        type: boolean
                    type: object
                required:
                - until
                type: object
              targetCluster:
                type: string
              targetTenant:
                type: string
            required:
            - restoreOption
            - restoreRole
            - source
            - targetCluster
            - targetTenant
            type: object
          status:
            description: OBTenantRestoreStatus defines the observed state of OBTenantRestore
            properties:
              operationContext:
                properties:
                  failureRule:
                    properties:
                      failureStatus:
                        type: string
                      failureStrategy:
                        type: string
                    required:
                    - failureStatus
                    - failureStrategy
                    type: object
                  idx:
                    type: integer
                  name:
                    type: string
                  targetStatus:
                    type: string
                  task:
                    type: string
                  taskId:
                    type: string
                  taskStatus:
                    type: string
                  tasks:
                    items:
                      type: string
                    type: array
                required:
                - idx
                - name
                - targetStatus
                - task
                - taskId
                - taskStatus
                - tasks
                type: object
              restoreProgress:
                description: RestoreHistory is the history of restore job, matches
                  view CDB_OB_RESTORE_HISTORY
                properties:
                  backup_cluster_name:
                    type: string
                  backup_cluster_version:
                    type: string
                  backup_dest:
                    type: string
                  backup_piece_list:
                    type: string
                  backup_set_list:
                    type: string
                  backup_tenant_id:
                    format: int64
                    type: integer
                  backup_tenant_name:
                    type: string
                  description:
                    type: string
                  finish_bytes:
                    format: int64
                    type: integer
                  finish_bytes_display:
                    type: string
                  finish_ls_count:
                    format: int64
                    type: integer
                  finish_tablet_count:
                    format: int64
                    type: integer
                  finish_timestamp:
                    type: string
                  job_id:
                    format: int64
                    type: integer
                  ls_count:
                    format: int64
                    type: integer
                  restore_option:
                    type: string
                  restore_scn:
                    format: int64
                    type: integer
                  restore_scn_display:
                    type: string
                  restore_tenant_id:
                    format: int64
                    type: integer
                  restore_tenant_name:
                    type: string
                  start_timestamp:
                    type: string
                  status:
                    type: string
                  tablet_count:
                    format: int64
                    type: integer
                  tenant_id:
                    format: int64
                    type: integer
                  total_bytes:
                    format: int64
                    type: integer
                  total_bytes_display:
                    type: string
                required:
                - backup_cluster_name
                - backup_cluster_version
                - backup_dest
                - backup_piece_list
                - backup_set_list
                - backup_tenant_id
                - backup_tenant_name
                - finish_ls_count
                - finish_tablet_count
                - finish_timestamp
                - job_id
                - ls_count
                - restore_option
                - restore_scn
                - restore_scn_display
                - restore_tenant_id
                - restore_tenant_name
                - start_timestamp
                - status
                - tablet_count
                - tenant_id
                type: object
              status:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                type: string
            required:
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
